### ISSUE TITLE
White background in PyCharm 2023.2.1

### ISSUE THREAD

**Issue by DusekM98** [AradiPatrik/one-dark-native-intellij#6]
For some reason, the theme started showing a white background in the main editor window. It began after the last update.
![Snímek obrazovky 2023-09-22 003128](https://github.com/AradiPatrik/one-dark-native-intellij/assets/78905048/ec91efe2-e964-4b84-a561-fd76f2d10b89)

**Comment by AradiPatrik** [comment]
https://github.com/AradiPatrik/one-dark-native-intellij/issues/3#issuecomment-1521156456

Thanks for the report and your interest in this theme!

Sorry it seems like I need to refactor the project to be able to release a new version to the plugin page. You are more than welcome to do the necessary steps to be able to release this plugin once again and fix the white background issue.

docs for theme development: https://plugins.jetbrains.com/docs/intellij/themes-getting-started.html
docs for deploying plugin: https://plugins.jetbrains.com/docs/intellij/developing-plugins.html

Let me know if you need further assistance! Awaiting your PR :)

**Comment by DusekM98** [comment]
I went through the docs and some JetBrains support chats and found out that I had to manually switch the Color Scheme Settings to one-dark-native (changing theme wont update that). Probably related to PyCharm update.
